# Generated by Django 3.0.3 on 2020-05-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_last_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'administrateur'), ('MANAGER', 'manager')], default='manager', max_length=15),
        ),
    ]
