# Generated by Django 3.0.3 on 2020-03-16 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repertoire_id', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote', models.CharField(max_length=1)),
                ('nom', models.CharField(max_length=200)),
                ('tag', models.CharField(default='serie', max_length=10)),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.Repertoire')),
            ],
        ),
        migrations.CreateModel(
            name='SousSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote', models.CharField(max_length=10, unique=True)),
                ('numero', models.PositiveIntegerField(default=0, max_length=3)),
                ('nom', models.CharField(max_length=200)),
                ('tag', models.CharField(default='sousserie', max_length=10)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote', models.CharField(max_length=20, unique=True)),
                ('numero', models.PositiveIntegerField(default=0, max_length=3)),
                ('nom', models.CharField(max_length=200)),
                ('nombre_arc', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(default='division', max_length=10)),
                ('sousserie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.SousSerie')),
            ],
        ),
        migrations.CreateModel(
            name='Boite_archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre_doc', models.PositiveIntegerField(default=0)),
                ('emplacement', models.TextField()),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.Repertoire')),
            ],
        ),
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote', models.CharField(max_length=30, unique=True)),
                ('numero', models.PositiveIntegerField(default=0, max_length=10)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('dateAjout', models.DateField(default=datetime.date.today)),
                ('present', models.BooleanField(default=True)),
                ('nbrSousDoc', models.PositiveIntegerField(default=1)),
                ('dateExtrem_min', models.DateField()),
                ('dateExtrem_max', models.DateField()),
                ('dua', models.DateField()),
                ('tag', models.CharField(default='archive', max_length=10)),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.Boite_archive')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.Division')),
            ],
        ),
    ]
