# Generated by Django 3.0.3 on 2020-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='division',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sousserie',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
