# Generated by Django 3.0.3 on 2020-03-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_auto_20200328_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='repertoireID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='division',
            name='repertoireID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
