# Generated by Django 3.0.3 on 2020-04-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0004_auto_20200328_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='cote',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='division',
            name='cote',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sousserie',
            name='cote',
            field=models.CharField(max_length=10),
        ),
    ]
