# Generated by Django 3.0.3 on 2020-04-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0005_auto_20200418_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertoire',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
