# Generated by Django 3.0.3 on 2020-04-27 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import repertoire.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repertoire', '0006_repertoire_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='creer_par',
            field=models.ForeignKey(default=1, on_delete=models.SET(repertoire.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='creer_par',
            field=models.ForeignKey(default=1, on_delete=models.SET(repertoire.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repertoire',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='myrepertoire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repertoire',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serie',
            name='creer_par',
            field=models.ForeignKey(default=1, on_delete=models.SET(repertoire.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sousserie',
            name='creer_par',
            field=models.ForeignKey(default=1, on_delete=models.SET(repertoire.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
