# Generated by Django 3.0.3 on 2020-05-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0007_auto_20200426_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archives',
            options={'ordering': ('cote',)},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('cote',)},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ('cote',)},
        ),
        migrations.AlterModelOptions(
            name='sousserie',
            options={'ordering': ('cote',)},
        ),
    ]
